#!/usr/bin/env bash

SRC_DIR='src'

BUILD_DIR='build'
JAVAC_FLAGS=(-d "$BUILD_DIR")

BIN_DIR='bin'
JAR_NAME='Nexus.jar'
MANIFEST_NAME='manifest.txt'

JAR_FLAGS=(cfm "$JAR_NAME" "$MANIFEST_NAME" -C "$BUILD_DIR" .)

mkdir "$BUILD_DIR" "$BIN_DIR" 2>/dev/null

SOURCES=()
while read -r src; do
    SOURCES+=("$src")
done < <(find "$SRC_DIR" -name '*.java')

javac "${JAVAC_FLAGS[@]}" "${SOURCES[@]:?}" || {
    echo 'failed to build classes!'
    exit 1
}

jar "${JAR_FLAGS[@]}" || {
    echo 'failed to create the jar'
    exit 1
}

echo 'Build successfully!'
